### ISSUE TITLE
capabilities.EndpointAnsible vs capabilities.Endpoint.Ansible

### ISSUE THREAD

**Issue by milesstoetzner** [onecommons/unfurl#296]
When I was debugging some problems, I came across the following line and without understanding what is going on there: is there a `.` missing between `Endpoint` and `Ansible`? 

https://github.com/onecommons/unfurl/blob/a34e29ba120d2db0afe297c8ce23c7ff7ffe4f26/unfurl/tosca_plugins/tosca_ext.py#L139

Best Greetings
Miles

**Comment by aszs** [comment]
That's as designed: Python identifiers can't have '.' so that's how conversion algorithm converts the name... if you look at the definition of `class EndpointAnsible` you'll see the TOSCA name:

https://github.com/onecommons/unfurl/blob/a34e29ba120d2db0afe297c8ce23c7ff7ffe4f26/unfurl/tosca_plugins/tosca_ext.py#L81
